import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Muskles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link
        rel="preload"
        href="/fonts/cartoonist_kooky.ttf"
        as="font"
        type="font/ttf"
        crossOrigin="anonymous"
      />
    </head>
    <body className="font-kooky text-foreground">
      {/* <Navbar /> */}
      {children}
      </body>
  </html>
  );
}
